// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v3.20.3
// source: cmd/comet/comet.proto

package comet

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	CometService_PushMsg_FullMethodName  = "/comet.CometService/PushMsg"
	CometService_PushRoom_FullMethodName = "/comet.CometService/PushRoom"
)

// CometServiceClient is the client API for CometService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// Comet 服务定义
type CometServiceClient interface {
	// 推送消息给单个用户
	PushMsg(ctx context.Context, in *PushMsgReq, opts ...grpc.CallOption) (*PushMsgReply, error)
	// 推送消息给房间
	PushRoom(ctx context.Context, in *PushRoomReq, opts ...grpc.CallOption) (*PushRoomReply, error)
}

type cometServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewCometServiceClient(cc grpc.ClientConnInterface) CometServiceClient {
	return &cometServiceClient{cc}
}

func (c *cometServiceClient) PushMsg(ctx context.Context, in *PushMsgReq, opts ...grpc.CallOption) (*PushMsgReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PushMsgReply)
	err := c.cc.Invoke(ctx, CometService_PushMsg_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *cometServiceClient) PushRoom(ctx context.Context, in *PushRoomReq, opts ...grpc.CallOption) (*PushRoomReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PushRoomReply)
	err := c.cc.Invoke(ctx, CometService_PushRoom_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// CometServiceServer is the server API for CometService service.
// All implementations must embed UnimplementedCometServiceServer
// for forward compatibility.
//
// Comet 服务定义
type CometServiceServer interface {
	// 推送消息给单个用户
	PushMsg(context.Context, *PushMsgReq) (*PushMsgReply, error)
	// 推送消息给房间
	PushRoom(context.Context, *PushRoomReq) (*PushRoomReply, error)
	mustEmbedUnimplementedCometServiceServer()
}

// UnimplementedCometServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedCometServiceServer struct{}

func (UnimplementedCometServiceServer) PushMsg(context.Context, *PushMsgReq) (*PushMsgReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method PushMsg not implemented")
}
func (UnimplementedCometServiceServer) PushRoom(context.Context, *PushRoomReq) (*PushRoomReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method PushRoom not implemented")
}
func (UnimplementedCometServiceServer) mustEmbedUnimplementedCometServiceServer() {}
func (UnimplementedCometServiceServer) testEmbeddedByValue()                      {}

// UnsafeCometServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to CometServiceServer will
// result in compilation errors.
type UnsafeCometServiceServer interface {
	mustEmbedUnimplementedCometServiceServer()
}

func RegisterCometServiceServer(s grpc.ServiceRegistrar, srv CometServiceServer) {
	// If the following call pancis, it indicates UnimplementedCometServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&CometService_ServiceDesc, srv)
}

func _CometService_PushMsg_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PushMsgReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CometServiceServer).PushMsg(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CometService_PushMsg_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CometServiceServer).PushMsg(ctx, req.(*PushMsgReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _CometService_PushRoom_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PushRoomReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CometServiceServer).PushRoom(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CometService_PushRoom_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CometServiceServer).PushRoom(ctx, req.(*PushRoomReq))
	}
	return interceptor(ctx, in, info, handler)
}

// CometService_ServiceDesc is the grpc.ServiceDesc for CometService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var CometService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "comet.CometService",
	HandlerType: (*CometServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "PushMsg",
			Handler:    _CometService_PushMsg_Handler,
		},
		{
			MethodName: "PushRoom",
			Handler:    _CometService_PushRoom_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "cmd/comet/comet.proto",
}
