// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.5
// 	protoc        v3.20.3
// source: cmd/comet/comet.proto

package comet

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// 推送消息请求
type PushMsgReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"` // 用户ID
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`             // 消息内容（JSON字符串）
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PushMsgReq) Reset() {
	*x = PushMsgReq{}
	mi := &file_cmd_comet_comet_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PushMsgReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PushMsgReq) ProtoMessage() {}

func (x *PushMsgReq) ProtoReflect() protoreflect.Message {
	mi := &file_cmd_comet_comet_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PushMsgReq.ProtoReflect.Descriptor instead.
func (*PushMsgReq) Descriptor() ([]byte, []int) {
	return file_cmd_comet_comet_proto_rawDescGZIP(), []int{0}
}

func (x *PushMsgReq) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *PushMsgReq) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

// 推送消息响应
type PushMsgReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          int32                  `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"` // 0-成功，其他-失败
	Msg           string                 `protobuf:"bytes,2,opt,name=msg,proto3" json:"msg,omitempty"`    // 响应消息
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PushMsgReply) Reset() {
	*x = PushMsgReply{}
	mi := &file_cmd_comet_comet_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PushMsgReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PushMsgReply) ProtoMessage() {}

func (x *PushMsgReply) ProtoReflect() protoreflect.Message {
	mi := &file_cmd_comet_comet_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PushMsgReply.ProtoReflect.Descriptor instead.
func (*PushMsgReply) Descriptor() ([]byte, []int) {
	return file_cmd_comet_comet_proto_rawDescGZIP(), []int{1}
}

func (x *PushMsgReply) GetCode() int32 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *PushMsgReply) GetMsg() string {
	if x != nil {
		return x.Msg
	}
	return ""
}

// 推送房间消息请求
type PushRoomReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RoomId        string                 `protobuf:"bytes,1,opt,name=room_id,json=roomId,proto3" json:"room_id,omitempty"`    // 房间ID
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`                // 消息内容（JSON字符串）
	UserIds       []string               `protobuf:"bytes,3,rep,name=user_ids,json=userIds,proto3" json:"user_ids,omitempty"` // 房间成员列表
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PushRoomReq) Reset() {
	*x = PushRoomReq{}
	mi := &file_cmd_comet_comet_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PushRoomReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PushRoomReq) ProtoMessage() {}

func (x *PushRoomReq) ProtoReflect() protoreflect.Message {
	mi := &file_cmd_comet_comet_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PushRoomReq.ProtoReflect.Descriptor instead.
func (*PushRoomReq) Descriptor() ([]byte, []int) {
	return file_cmd_comet_comet_proto_rawDescGZIP(), []int{2}
}

func (x *PushRoomReq) GetRoomId() string {
	if x != nil {
		return x.RoomId
	}
	return ""
}

func (x *PushRoomReq) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *PushRoomReq) GetUserIds() []string {
	if x != nil {
		return x.UserIds
	}
	return nil
}

// 推送房间消息响应
type PushRoomReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          int32                  `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"` // 0-成功，其他-失败
	Msg           string                 `protobuf:"bytes,2,opt,name=msg,proto3" json:"msg,omitempty"`    // 响应消息
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PushRoomReply) Reset() {
	*x = PushRoomReply{}
	mi := &file_cmd_comet_comet_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PushRoomReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PushRoomReply) ProtoMessage() {}

func (x *PushRoomReply) ProtoReflect() protoreflect.Message {
	mi := &file_cmd_comet_comet_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PushRoomReply.ProtoReflect.Descriptor instead.
func (*PushRoomReply) Descriptor() ([]byte, []int) {
	return file_cmd_comet_comet_proto_rawDescGZIP(), []int{3}
}

func (x *PushRoomReply) GetCode() int32 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *PushRoomReply) GetMsg() string {
	if x != nil {
		return x.Msg
	}
	return ""
}

var File_cmd_comet_comet_proto protoreflect.FileDescriptor

var file_cmd_comet_comet_proto_rawDesc = string([]byte{
	0x0a, 0x15, 0x63, 0x6d, 0x64, 0x2f, 0x63, 0x6f, 0x6d, 0x65, 0x74, 0x2f, 0x63, 0x6f, 0x6d, 0x65,
	0x74, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x05, 0x63, 0x6f, 0x6d, 0x65, 0x74, 0x22, 0x3f,
	0x0a, 0x0a, 0x50, 0x75, 0x73, 0x68, 0x4d, 0x73, 0x67, 0x52, 0x65, 0x71, 0x12, 0x17, 0x0a, 0x07,
	0x75, 0x73, 0x65, 0x72, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x75,
	0x73, 0x65, 0x72, 0x49, 0x64, 0x12, 0x18, 0x0a, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x22,
	0x34, 0x0a, 0x0c, 0x50, 0x75, 0x73, 0x68, 0x4d, 0x73, 0x67, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x12,
	0x12, 0x0a, 0x04, 0x63, 0x6f, 0x64, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x04, 0x63,
	0x6f, 0x64, 0x65, 0x12, 0x10, 0x0a, 0x03, 0x6d, 0x73, 0x67, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x03, 0x6d, 0x73, 0x67, 0x22, 0x5b, 0x0a, 0x0b, 0x50, 0x75, 0x73, 0x68, 0x52, 0x6f, 0x6f,
	0x6d, 0x52, 0x65, 0x71, 0x12, 0x17, 0x0a, 0x07, 0x72, 0x6f, 0x6f, 0x6d, 0x5f, 0x69, 0x64, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x72, 0x6f, 0x6f, 0x6d, 0x49, 0x64, 0x12, 0x18, 0x0a,
	0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07,
	0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x12, 0x19, 0x0a, 0x08, 0x75, 0x73, 0x65, 0x72, 0x5f,
	0x69, 0x64, 0x73, 0x18, 0x03, 0x20, 0x03, 0x28, 0x09, 0x52, 0x07, 0x75, 0x73, 0x65, 0x72, 0x49,
	0x64, 0x73, 0x22, 0x35, 0x0a, 0x0d, 0x50, 0x75, 0x73, 0x68, 0x52, 0x6f, 0x6f, 0x6d, 0x52, 0x65,
	0x70, 0x6c, 0x79, 0x12, 0x12, 0x0a, 0x04, 0x63, 0x6f, 0x64, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x05, 0x52, 0x04, 0x63, 0x6f, 0x64, 0x65, 0x12, 0x10, 0x0a, 0x03, 0x6d, 0x73, 0x67, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x6d, 0x73, 0x67, 0x32, 0x77, 0x0a, 0x0c, 0x43, 0x6f, 0x6d,
	0x65, 0x74, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x31, 0x0a, 0x07, 0x50, 0x75, 0x73,
	0x68, 0x4d, 0x73, 0x67, 0x12, 0x11, 0x2e, 0x63, 0x6f, 0x6d, 0x65, 0x74, 0x2e, 0x50, 0x75, 0x73,
	0x68, 0x4d, 0x73, 0x67, 0x52, 0x65, 0x71, 0x1a, 0x13, 0x2e, 0x63, 0x6f, 0x6d, 0x65, 0x74, 0x2e,
	0x50, 0x75, 0x73, 0x68, 0x4d, 0x73, 0x67, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x12, 0x34, 0x0a, 0x08,
	0x50, 0x75, 0x73, 0x68, 0x52, 0x6f, 0x6f, 0x6d, 0x12, 0x12, 0x2e, 0x63, 0x6f, 0x6d, 0x65, 0x74,
	0x2e, 0x50, 0x75, 0x73, 0x68, 0x52, 0x6f, 0x6f, 0x6d, 0x52, 0x65, 0x71, 0x1a, 0x14, 0x2e, 0x63,
	0x6f, 0x6d, 0x65, 0x74, 0x2e, 0x50, 0x75, 0x73, 0x68, 0x52, 0x6f, 0x6f, 0x6d, 0x52, 0x65, 0x70,
	0x6c, 0x79, 0x42, 0x17, 0x5a, 0x15, 0x73, 0x69, 0x6d, 0x70, 0x6c, 0x65, 0x2d, 0x69, 0x6d, 0x76,
	0x32, 0x2f, 0x61, 0x70, 0x69, 0x2f, 0x63, 0x6f, 0x6d, 0x65, 0x74, 0x62, 0x06, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x33,
})

var (
	file_cmd_comet_comet_proto_rawDescOnce sync.Once
	file_cmd_comet_comet_proto_rawDescData []byte
)

func file_cmd_comet_comet_proto_rawDescGZIP() []byte {
	file_cmd_comet_comet_proto_rawDescOnce.Do(func() {
		file_cmd_comet_comet_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_cmd_comet_comet_proto_rawDesc), len(file_cmd_comet_comet_proto_rawDesc)))
	})
	return file_cmd_comet_comet_proto_rawDescData
}

var file_cmd_comet_comet_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_cmd_comet_comet_proto_goTypes = []any{
	(*PushMsgReq)(nil),    // 0: comet.PushMsgReq
	(*PushMsgReply)(nil),  // 1: comet.PushMsgReply
	(*PushRoomReq)(nil),   // 2: comet.PushRoomReq
	(*PushRoomReply)(nil), // 3: comet.PushRoomReply
}
var file_cmd_comet_comet_proto_depIdxs = []int32{
	0, // 0: comet.CometService.PushMsg:input_type -> comet.PushMsgReq
	2, // 1: comet.CometService.PushRoom:input_type -> comet.PushRoomReq
	1, // 2: comet.CometService.PushMsg:output_type -> comet.PushMsgReply
	3, // 3: comet.CometService.PushRoom:output_type -> comet.PushRoomReply
	2, // [2:4] is the sub-list for method output_type
	0, // [0:2] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_cmd_comet_comet_proto_init() }
func file_cmd_comet_comet_proto_init() {
	if File_cmd_comet_comet_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_cmd_comet_comet_proto_rawDesc), len(file_cmd_comet_comet_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_cmd_comet_comet_proto_goTypes,
		DependencyIndexes: file_cmd_comet_comet_proto_depIdxs,
		MessageInfos:      file_cmd_comet_comet_proto_msgTypes,
	}.Build()
	File_cmd_comet_comet_proto = out.File
	file_cmd_comet_comet_proto_goTypes = nil
	file_cmd_comet_comet_proto_depIdxs = nil
}
